name: bug report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: desktop-os
    attributes:
      label: Desktop OS
    validations:
      required: true
  - type: input
    id: desktop-browser
    attributes:
      label: Desktop Browser
    validations:
      required: true
  - type: input
    id: desktop-version
    attributes:
      label: Desktop Version
    validations:
      required: true
  - type: input
    id: smartphone-device
    attributes:
      label: Smartphone Device
    validations:
      required: false
  - type: input
    id: smartphone-os
    attributes:
      label: Smartphone OS
    validations:
      required: false
  - type: input
    id: smartphone-browser
    attributes:
      label: Smartphone Browser
    validations:
      required: false
  - type: input
    id: smartphone-version
    attributes:
      label: Smartphone Version
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
